projects:
  app:
    schemaPath: src/generated/schema.graphql
    extensions:
      endpoints:
        prod: 'http://localhost:4000'
        dev: 'http://localhost:4000'
  db:
    schemaPath: src/generated/schema.graphql
    extensions:
      endpoints:
        prod: 'http://localhost:4000'
        dev: 'http://localhost:4000'
